// ShellEx.idl : ShellEx 的 IDL 源
//

// 此文件将由 MIDL 工具处理以
// 产生类型库(ShellEx.tlb)和封送处理代码。

import "oaidl.idl";
import "ocidl.idl";

[
	object,
	uuid(4C2F6DD5-556D-465E-A75F-08CE3826E6F5),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IOverlayIcon : IDispatch{
};
[
	object,
	uuid(68C6FAD9-8EF3-4D40-8F66-73FF3FFE3134),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IContextMenuEx : IDispatch{
};
[
	object,
	uuid(707999AD-02F0-497A-AC71-3AB957347EC2),
	dual,
	nonextensible,
	pointer_default(unique)
]
interface IPropPageEx : IDispatch{
};
[
	uuid(1AD8F1E0-94CA-4F4E-8086-A138EFAD6497),
	version(1.0),
]
library ShellExLib
{
	importlib("stdole2.tlb");
	[		
		uuid(C339E6B5-55AF-41E1-91C6-FF5B669D244E)		
	]
	coclass OverlayIcon
	{
		[default] interface IOverlayIcon;
	};
	[		
		uuid(A4250BAE-CDC3-48F9-A25B-9CFEAFEED05A)		
	]
	coclass ContextMenuEx
	{
		[default] interface IContextMenuEx;
	};
	[		
		uuid(E3D874A1-F261-48F5-9DE6-9E12D50C9BB4)		
	]
	coclass PropPageEx
	{
		[default] interface IPropPageEx;
	};
};

